export const goAPI_cities = [
  // { id: "11.01", name: "KAB. ACEH SELATAN" },
  // { id: "11.02", name: "KAB. ACEH TENGGARA" },
  // { id: "11.03", name: "KAB. ACEH TIMUR" },
  // { id: "11.04", name: "KAB. ACEH TENGAH" },
  // { id: "11.05", name: "KAB. ACEH BARAT" },
  // { id: "11.06", name: "KAB. ACEH BESAR" },
  // { id: "11.07", name: "KAB. PIDIE" },
  // { id: "11.08", name: "KAB. ACEH UTARA" },
  // { id: "11.09", name: "KAB. SIMEULUE" },
  // { id: "11.10", name: "KAB. ACEH SINGKIL" },
  // { id: "11.11", name: "KAB. BIREUEN" },
  // { id: "11.12", name: "KAB. ACEH BARAT DAYA" },
  // { id: "11.13", name: "KAB. GAYO LUES" },
  // { id: "11.14", name: "KAB. ACEH JAYA" },
  // { id: "11.15", name: "KAB. NAGAN RAYA" },
  // { id: "11.16", name: "KAB. ACEH TAMIANG" },
  // { id: "11.17", name: "KAB. BENER MERIAH" },
  // { id: "11.18", name: "KAB. PIDIE JAYA" },
  // { id: "11.71", name: "KOTA BANDA ACEH" },
  // { id: "11.72", name: "KOTA SABANG" },
  // { id: "11.73", name: "KOTA LHOKSEUMAWE" },
  // { id: "11.74", name: "KOTA LANGSA" },
  // { id: "11.75", name: "KOTA SUBULUSSALAM" },
  // { id: "12.01", name: "KAB. TAPANULI TENGAH" },
  // { id: "12.02", name: "KAB. TAPANULI UTARA" },
  // { id: "12.03", name: "KAB. TAPANULI SELATAN" },
  // { id: "12.04", name: "KAB. NIAS" },
  // { id: "12.05", name: "KAB. LANGKAT" },
  // { id: "12.06", name: "KAB. KARO" },
  // { id: "12.07", name: "KAB. DELI SERDANG" },
  // { id: "12.08", name: "KAB. SIMALUNGUN" },
  // { id: "12.09", name: "KAB. ASAHAN" },
  // { id: "12.10", name: "KAB. LABUHANBATU" },
  // { id: "12.11", name: "KAB. DAIRI" },
  // { id: "12.12", name: "KAB. TOBA" },
  // { id: "12.13", name: "KAB. MANDAILING NATAL" },
  // { id: "12.14", name: "KAB. NIAS SELATAN" },
  // { id: "12.15", name: "KAB. PAKPAK BHARAT" },
  // { id: "12.16", name: "KAB. HUMBANG HASUNDUTAN" },
  // { id: "12.17", name: "KAB. SAMOSIR" },
  // { id: "12.18", name: "KAB. SERDANG BEDAGAI" },
  // { id: "12.19", name: "KAB. BATU BARA" },
  // { id: "12.20", name: "KAB. PADANG LAWAS UTARA" },
  // { id: "12.21", name: "KAB. PADANG LAWAS" },
  // { id: "12.22", name: "KAB. LABUHANBATU SELATAN" },
  // { id: "12.23", name: "KAB. LABUHANBATU UTARA" },
  // { id: "12.24", name: "KAB. NIAS UTARA" },
  // { id: "12.25", name: "KAB. NIAS BARAT" },
  // { id: "12.71", name: "KOTA MEDAN" },
  // { id: "12.72", name: "KOTA PEMATANGSIANTAR" },
  // { id: "12.73", name: "KOTA SIBOLGA" },
  // { id: "12.74", name: "KOTA TANJUNG BALAI" },
  // { id: "12.75", name: "KOTA BINJAI" },
  // { id: "12.76", name: "KOTA TEBING TINGGI" },
  // { id: "12.77", name: "KOTA PADANGSIDIMPUAN" },
  // { id: "12.78", name: "KOTA GUNUNGSITOLI" },
  // { id: "13.01", name: "KAB. PESISIR SELATAN" },
  // { id: "13.02", name: "KAB. SOLOK" },
  // { id: "13.03", name: "KAB. SIJUNJUNG" },
  // { id: "13.04", name: "KAB. TANAH DATAR" },
  // { id: "13.05", name: "KAB. PADANG PARIAMAN" },
  // { id: "13.06", name: "KAB. AGAM" },
  // { id: "13.07", name: "KAB. LIMA PULUH KOTA" },
  // { id: "13.08", name: "KAB. PASAMAN" },
  // { id: "13.09", name: "KAB. KEPULAUAN MENTAWAI" },
  // { id: "13.10", name: "KAB. DHARMASRAYA" },
  // { id: "13.11", name: "KAB. SOLOK SELATAN" },
  // { id: "13.12", name: "KAB. PASAMAN BARAT" },
  // { id: "13.71", name: "KOTA PADANG" },
  // { id: "13.72", name: "KOTA SOLOK" },
  // { id: "13.73", name: "KOTA SAWAHLUNTO" },
  // { id: "13.74", name: "KOTA PADANG PANJANG" },
  // { id: "13.75", name: "KOTA BUKITTINGGI" },
  // { id: "13.76", name: "KOTA PAYAKUMBUH" },
  // { id: "13.77", name: "KOTA PARIAMAN" },
  // { id: "14.01", name: "KAB. KAMPAR" },
  // { id: "14.02", name: "KAB. INDRAGIRI HULU" },
  // { id: "14.03", name: "KAB. BENGKALIS" },
  // { id: "14.04", name: "KAB. INDRAGIRI HILIR" },
  // { id: "14.05", name: "KAB. PELALAWAN" },
  // { id: "14.06", name: "KAB. ROKAN HULU" },
  // { id: "14.07", name: "KAB. ROKAN HILIR" },
  // { id: "14.08", name: "KAB. SIAK" },
  // { id: "14.09", name: "KAB. KUANTAN SINGINGI" },
  // { id: "14.10", name: "KAB. KEPULAUAN MERANTI" },
  { id: "14.71", name: "KOTA PEKANBARU" },
  // { id: "14.72", name: "KOTA DUMAI" },
  // { id: "15.01", name: "KAB. KERINCI" },
  // { id: "15.02", name: "KAB. MERANGIN" },
  // { id: "15.03", name: "KAB. SAROLANGUN" },
  // { id: "15.04", name: "KAB. BATANGHARI" },
  // { id: "15.05", name: "KAB. MUARO JAMBI" },
  // { id: "15.06", name: "KAB. TANJUNG JABUNG BARAT" },
  // { id: "15.07", name: "KAB. TANJUNG JABUNG TIMUR" },
  // { id: "15.08", name: "KAB. BUNGO" },
  // { id: "15.09", name: "KAB. TEBO" },
  // { id: "15.71", name: "KOTA JAMBI" },
  // { id: "15.72", name: "KOTA SUNGAI PENUH" },
  // { id: "16.01", name: "KAB. OGAN KOMERING ULU" },
  // { id: "16.02", name: "KAB. OGAN KOMERING ILIR" },
  // { id: "16.03", name: "KAB. MUARA ENIM" },
  // { id: "16.04", name: "KAB. LAHAT" },
  // { id: "16.05", name: "KAB. MUSI RAWAS" },
  // { id: "16.06", name: "KAB. MUSI BANYUASIN" },
  // { id: "16.07", name: "KAB. BANYUASIN" },
  // { id: "16.08", name: "KAB. OGAN KOMERING ULU TIMUR" },
  // { id: "16.09", name: "KAB. OGAN KOMERING ULU SELATAN" },
  // { id: "16.10", name: "KAB. OGAN ILIR" },
  // { id: "16.11", name: "KAB. EMPAT LAWANG" },
  // { id: "16.12", name: "KAB. PENUKAL ABAB LEMATANG ILIR" },
  // { id: "16.13", name: "KAB. MUSI RAWAS UTARA" },
  // { id: "16.71", name: "KOTA PALEMBANG" },
  // { id: "16.72", name: "KOTA PAGAR ALAM" },
  // { id: "16.73", name: "KOTA LUBUK LINGGAU" },
  // { id: "16.74", name: "KOTA PRABUMULIH" },
  // { id: "17.01", name: "KAB. BENGKULU SELATAN" },
  // { id: "17.02", name: "KAB. REJANG LEBONG" },
  // { id: "17.03", name: "KAB. BENGKULU UTARA" },
  // { id: "17.04", name: "KAB. KAUR" },
  // { id: "17.05", name: "KAB. SELUMA" },
  // { id: "17.06", name: "KAB. MUKO MUKO" },
  // { id: "17.07", name: "KAB. LEBONG" },
  // { id: "17.08", name: "KAB. KEPAHIANG" },
  // { id: "17.09", name: "KAB. BENGKULU TENGAH" },
  // { id: "17.71", name: "KOTA BENGKULU" },
  // { id: "18.01", name: "KAB. LAMPUNG SELATAN" },
  // { id: "18.02", name: "KAB. LAMPUNG TENGAH" },
  // { id: "18.03", name: "KAB. LAMPUNG UTARA" },
  // { id: "18.04", name: "KAB. LAMPUNG BARAT" },
  // { id: "18.05", name: "KAB. TULANG BAWANG" },
  // { id: "18.06", name: "KAB. TANGGAMUS" },
  // { id: "18.07", name: "KAB. LAMPUNG TIMUR" },
  // { id: "18.08", name: "KAB. WAY KANAN" },
  // { id: "18.09", name: "KAB. PESAWARAN" },
  // { id: "18.10", name: "KAB. PRINGSEWU" },
  // { id: "18.11", name: "KAB. MESUJI" },
  // { id: "18.12", name: "KAB. TULANG BAWANG BARAT" },
  // { id: "18.13", name: "KAB. PESISIR BARAT" },
  // { id: "18.71", name: "KOTA BANDAR LAMPUNG" },
  // { id: "18.72", name: "KOTA METRO" },
  // { id: "19.01", name: "KAB. BANGKA" },
  // { id: "19.02", name: "KAB. BELITUNG" },
  // { id: "19.03", name: "KAB. BANGKA SELATAN" },
  // { id: "19.04", name: "KAB. BANGKA TENGAH" },
  // { id: "19.05", name: "KAB. BANGKA BARAT" },
  // { id: "19.06", name: "KAB. BELITUNG TIMUR" },
  // { id: "19.71", name: "KOTA PANGKAL PINANG" },
  // { id: "21.01", name: "KAB. BINTAN" },
  // { id: "21.02", name: "KAB. KARIMUN" },
  // { id: "21.03", name: "KAB. NATUNA" },
  // { id: "21.04", name: "KAB. LINGGA" },
  // { id: "21.05", name: "KAB. KEPULAUAN ANAMBAS" },
  { id: "21.71", name: "KOTA BATAM" },
  // { id: "21.72", name: "KOTA TANJUNG PINANG" },
  // { id: "31.01", name: "KAB. ADM. KEP. SERIBU" },
  { id: "31.71", name: "KOTA ADM. JAKARTA PUSAT" },
  { id: "31.72", name: "KOTA ADM. JAKARTA UTARA" },
  { id: "31.73", name: "KOTA ADM. JAKARTA BARAT" },
  { id: "31.74", name: "KOTA ADM. JAKARTA SELATAN" },
  { id: "31.75", name: "KOTA ADM. JAKARTA TIMUR" },
  { id: "32.01", name: "KAB. BOGOR" },
  // { id: "32.02", name: "KAB. SUKABUMI" },
  // { id: "32.03", name: "KAB. CIANJUR" },
  { id: "32.04", name: "KAB. BANDUNG" },
  // { id: "32.05", name: "KAB. GARUT" },
  // { id: "32.06", name: "KAB. TASIKMALAYA" },
  // { id: "32.07", name: "KAB. CIAMIS" },
  // { id: "32.08", name: "KAB. KUNINGAN" },
  // { id: "32.09", name: "KAB. CIREBON" },
  // { id: "32.10", name: "KAB. MAJALENGKA" },
  // { id: "32.11", name: "KAB. SUMEDANG" },
  // { id: "32.12", name: "KAB. INDRAMAYU" },
  // { id: "32.13", name: "KAB. SUBANG" },
  // { id: "32.14", name: "KAB. PURWAKARTA" },
  // { id: "32.15", name: "KAB. KARAWANG" },
  { id: "32.16", name: "KAB. BEKASI" },
  { id: "32.17", name: "KAB. BANDUNG BARAT" },
  // { id: "32.18", name: "KAB. PANGANDARAN" },
  { id: "32.71", name: "KOTA BOGOR" },
  // { id: "32.72", name: "KOTA SUKABUMI" },
  { id: "32.73", name: "KOTA BANDUNG" },
  { id: "32.74", name: "KOTA CIREBON" },
  { id: "32.75", name: "KOTA BEKASI" },
  { id: "32.76", name: "KOTA DEPOK" },
  { id: "32.77", name: "KOTA CIMAHI" },
  // { id: "32.78", name: "KOTA TASIKMALAYA" },
  // { id: "32.79", name: "KOTA BANJAR" },
  // { id: "33.01", name: "KAB. CILACAP" },
  // { id: "33.02", name: "KAB. BANYUMAS" },
  // { id: "33.03", name: "KAB. PURBALINGGA" },
  // { id: "33.04", name: "KAB. BANJARNEGARA" },
  // { id: "33.05", name: "KAB. KEBUMEN" },
  // { id: "33.06", name: "KAB. PURWOREJO" },
  // { id: "33.07", name: "KAB. WONOSOBO" },
  // { id: "33.08", name: "KAB. MAGELANG" },
  // { id: "33.09", name: "KAB. BOYOLALI" },
  // { id: "33.10", name: "KAB. KLATEN" },
  // { id: "33.11", name: "KAB. SUKOHARJO" },
  // { id: "33.12", name: "KAB. WONOGIRI" },
  // { id: "33.13", name: "KAB. KARANGANYAR" },
  // { id: "33.14", name: "KAB. SRAGEN" },
  // { id: "33.15", name: "KAB. GROBOGAN" },
  // { id: "33.16", name: "KAB. BLORA" },
  // { id: "33.17", name: "KAB. REMBANG" },
  // { id: "33.18", name: "KAB. PATI" },
  // { id: "33.19", name: "KAB. KUDUS" },
  // { id: "33.20", name: "KAB. JEPARA" },
  // { id: "33.21", name: "KAB. DEMAK" },
  { id: "33.22", name: "KAB. SEMARANG" },
  // { id: "33.23", name: "KAB. TEMANGGUNG" },
  // { id: "33.24", name: "KAB. KENDAL" },
  // { id: "33.25", name: "KAB. BATANG" },
  // { id: "33.26", name: "KAB. PEKALONGAN" },
  // { id: "33.27", name: "KAB. PEMALANG" },
  // { id: "33.28", name: "KAB. TEGAL" },
  // { id: "33.29", name: "KAB. BREBES" },
  // { id: "33.71", name: "KOTA MAGELANG" },
  // { id: "33.72", name: "KOTA SURAKARTA" },
  // { id: "33.73", name: "KOTA SALATIGA" },
  { id: "33.74", name: "KOTA SEMARANG" },
  // { id: "33.75", name: "KOTA PEKALONGAN" },
  // { id: "33.76", name: "KOTA TEGAL" },
  // { id: "34.01", name: "KAB. KULON PROGO" },
  // { id: "34.02", name: "KAB. BANTUL" },
  // { id: "34.03", name: "KAB. GUNUNGKIDUL" },
  { id: "34.04", name: "KAB. SLEMAN" },
  { id: "34.71", name: "KOTA YOGYAKARTA" },
  // { id: "35.01", name: "KAB. PACITAN" },
  // { id: "35.02", name: "KAB. PONOROGO" },
  // { id: "35.03", name: "KAB. TRENGGALEK" },
  // { id: "35.04", name: "KAB. TULUNGAGUNG" },
  // { id: "35.05", name: "KAB. BLITAR" },
  // { id: "35.06", name: "KAB. KEDIRI" },
  // { id: "35.07", name: "KAB. MALANG" },
  // { id: "35.08", name: "KAB. LUMAJANG" },
  // { id: "35.09", name: "KAB. JEMBER" },
  // { id: "35.10", name: "KAB. BANYUWANGI" },
  // { id: "35.11", name: "KAB. BONDOWOSO" },
  // { id: "35.12", name: "KAB. SITUBONDO" },
  // { id: "35.13", name: "KAB. PROBOLINGGO" },
  // { id: "35.14", name: "KAB. PASURUAN" },
  // { id: "35.15", name: "KAB. SIDOARJO" },
  // { id: "35.16", name: "KAB. MOJOKERTO" },
  // { id: "35.17", name: "KAB. JOMBANG" },
  // { id: "35.18", name: "KAB. NGANJUK" },
  // { id: "35.19", name: "KAB. MADIUN" },
  // { id: "35.20", name: "KAB. MAGETAN" },
  // { id: "35.21", name: "KAB. NGAWI" },
  // { id: "35.22", name: "KAB. BOJONEGORO" },
  // { id: "35.23", name: "KAB. TUBAN" },
  // { id: "35.24", name: "KAB. LAMONGAN" },
  // { id: "35.25", name: "KAB. GRESIK" },
  // { id: "35.26", name: "KAB. BANGKALAN" },
  // { id: "35.27", name: "KAB. SAMPANG" },
  // { id: "35.28", name: "KAB. PAMEKASAN" },
  // { id: "35.29", name: "KAB. SUMENEP" },
  // { id: "35.71", name: "KOTA KEDIRI" },
  // { id: "35.72", name: "KOTA BLITAR" },
  { id: "35.73", name: "KOTA MALANG" },
  // { id: "35.74", name: "KOTA PROBOLINGGO" },
  // { id: "35.75", name: "KOTA PASURUAN" },
  // { id: "35.76", name: "KOTA MOJOKERTO" },
  // { id: "35.77", name: "KOTA MADIUN" },
  { id: "35.78", name: "KOTA SURABAYA" },
  // { id: "35.79", name: "KOTA BATU" },
  // { id: "36.01", name: "KAB. PANDEGLANG" },
  // { id: "36.02", name: "KAB. LEBAK" },
  { id: "36.03", name: "KAB. TANGERANG" },
  // { id: "36.04", name: "KAB. SERANG" },
  { id: "36.71", name: "KOTA TANGERANG" },
  // { id: "36.72", name: "KOTA CILEGON" },
  // { id: "36.73", name: "KOTA SERANG" },
  { id: "36.74", name: "KOTA TANGERANG SELATAN" },
  // { id: "51.01", name: "KAB. JEMBRANA" },
  // { id: "51.02", name: "KAB. TABANAN" },
  // { id: "51.03", name: "KAB. BADUNG" },
  // { id: "51.04", name: "KAB. GIANYAR" },
  // { id: "51.05", name: "KAB. KLUNGKUNG" },
  // { id: "51.06", name: "KAB. BANGLI" },
  // { id: "51.07", name: "KAB. KARANGASEM" },
  // { id: "51.08", name: "KAB. BULELENG" },
  // { id: "51.71", name: "KOTA DENPASAR" },
  // { id: "52.01", name: "KAB. LOMBOK BARAT" },
  // { id: "52.02", name: "KAB. LOMBOK TENGAH" },
  // { id: "52.03", name: "KAB. LOMBOK TIMUR" },
  // { id: "52.04", name: "KAB. SUMBAWA" },
  // { id: "52.05", name: "KAB. DOMPU" },
  // { id: "52.06", name: "KAB. BIMA" },
  // { id: "52.07", name: "KAB. SUMBAWA BARAT" },
  // { id: "52.08", name: "KAB. LOMBOK UTARA" },
  // { id: "52.71", name: "KOTA MATARAM" },
  // { id: "52.72", name: "KOTA BIMA" },
  // { id: "53.01", name: "KAB. KUPANG" },
  // { id: "53.02", name: "KAB TIMOR TENGAH SELATAN" },
  // { id: "53.03", name: "KAB. TIMOR TENGAH UTARA" },
  // { id: "53.04", name: "KAB. BELU" },
  // { id: "53.05", name: "KAB. ALOR" },
  // { id: "53.06", name: "KAB. FLORES TIMUR" },
  // { id: "53.07", name: "KAB. SIKKA" },
  // { id: "53.08", name: "KAB. ENDE" },
  // { id: "53.09", name: "KAB. NGADA" },
  // { id: "53.10", name: "KAB. MANGGARAI" },
  // { id: "53.11", name: "KAB. SUMBA TIMUR" },
  // { id: "53.12", name: "KAB. SUMBA BARAT" },
  // { id: "53.13", name: "KAB. LEMBATA" },
  // { id: "53.14", name: "KAB. ROTE NDAO" },
  // { id: "53.15", name: "KAB. MANGGARAI BARAT" },
  // { id: "53.16", name: "KAB. NAGEKEO" },
  // { id: "53.17", name: "KAB. SUMBA TENGAH" },
  // { id: "53.18", name: "KAB. SUMBA BARAT DAYA" },
  // { id: "53.19", name: "KAB. MANGGARAI TIMUR" },
  // { id: "53.20", name: "KAB. SABU RAIJUA" },
  // { id: "53.21", name: "KAB. MALAKA" },
  // { id: "53.71", name: "KOTA KUPANG" },
  // { id: "61.01", name: "KAB. SAMBAS" },
  // { id: "61.02", name: "KAB. MEMPAWAH" },
  // { id: "61.03", name: "KAB. SANGGAU" },
  // { id: "61.04", name: "KAB. KETAPANG" },
  // { id: "61.05", name: "KAB. SINTANG" },
  // { id: "61.06", name: "KAB. KAPUAS HULU" },
  // { id: "61.07", name: "KAB. BENGKAYANG" },
  // { id: "61.08", name: "KAB. LANDAK" },
  // { id: "61.09", name: "KAB. SEKADAU" },
  // { id: "61.10", name: "KAB. MELAWI" },
  // { id: "61.11", name: "KAB. KAYONG UTARA" },
  // { id: "61.12", name: "KAB. KUBU RAYA" },
  // { id: "61.71", name: "KOTA PONTIANAK" },
  // { id: "61.72", name: "KOTA SINGKAWANG" },
  // { id: "62.01", name: "KAB. KOTAWARINGIN BARAT" },
  // { id: "62.02", name: "KAB. KOTAWARINGIN TIMUR" },
  // { id: "62.03", name: "KAB. KAPUAS" },
  // { id: "62.04", name: "KAB. BARITO SELATAN" },
  // { id: "62.05", name: "KAB. BARITO UTARA" },
  // { id: "62.06", name: "KAB. KATINGAN" },
  // { id: "62.07", name: "KAB. SERUYAN" },
  // { id: "62.08", name: "KAB. SUKAMARA" },
  // { id: "62.09", name: "KAB. LAMANDAU" },
  // { id: "62.10", name: "KAB. GUNUNG MAS" },
  // { id: "62.11", name: "KAB. PULANG PISAU" },
  // { id: "62.12", name: "KAB. MURUNG RAYA" },
  // { id: "62.13", name: "KAB. BARITO TIMUR" },
  // { id: "62.71", name: "KOTA PALANGKARAYA" },
  // { id: "63.01", name: "KAB. TANAH LAUT" },
  // { id: "63.02", name: "KAB. KOTABARU" },
  // { id: "63.03", name: "KAB. BANJAR" },
  // { id: "63.04", name: "KAB. BARITO KUALA" },
  // { id: "63.05", name: "KAB. TAPIN" },
  // { id: "63.06", name: "KAB. HULU SUNGAI SELATAN" },
  // { id: "63.07", name: "KAB. HULU SUNGAI TENGAH" },
  // { id: "63.08", name: "KAB. HULU SUNGAI UTARA" },
  // { id: "63.09", name: "KAB. TABALONG" },
  // { id: "63.10", name: "KAB. TANAH BUMBU" },
  // { id: "63.11", name: "KAB. BALANGAN" },
  // { id: "63.71", name: "KOTA BANJARMASIN" },
  // { id: "63.72", name: "KOTA BANJARBARU" },
  // { id: "64.01", name: "KAB. PASER" },
  // { id: "64.02", name: "KAB. KUTAI KARTANEGARA" },
  // { id: "64.03", name: "KAB. BERAU" },
  // { id: "64.07", name: "KAB. KUTAI BARAT" },
  // { id: "64.08", name: "KAB. KUTAI TIMUR" },
  // { id: "64.09", name: "KAB. PENAJAM PASER UTARA" },
  // { id: "64.11", name: "KAB. MAHAKAM ULU" },
  // { id: "64.71", name: "KOTA BALIKPAPAN" },
  // { id: "64.72", name: "KOTA SAMARINDA" },
  // { id: "64.74", name: "KOTA BONTANG" },
  // { id: "65.01", name: "KAB. BULUNGAN" },
  // { id: "65.02", name: "KAB. MALINAU" },
  // { id: "65.03", name: "KAB. NUNUKAN" },
  // { id: "65.04", name: "KAB. TANA TIDUNG" },
  // { id: "65.71", name: "KOTA TARAKAN" },
  // { id: "71.01", name: "KAB. BOLAANG MONGONDOW" },
  // { id: "71.02", name: "KAB. MINAHASA" },
  // { id: "71.03", name: "KAB. KEPULAUAN SANGIHE" },
  // { id: "71.04", name: "KAB. KEPULAUAN TALAUD" },
  // { id: "71.05", name: "KAB. MINAHASA SELATAN" },
  // { id: "71.06", name: "KAB. MINAHASA UTARA" },
  // { id: "71.07", name: "KAB. MINAHASA TENGGARA" },
  // { id: "71.08", name: "KAB. BOLAANG MONGONDOW UTARA" },
  // { id: "71.09", name: "KAB. KEP. SIAU TAGULANDANG BIARO" },
  // { id: "71.10", name: "KAB. BOLAANG MONGONDOW TIMUR" },
  // { id: "71.11", name: "KAB. BOLAANG MONGONDOW SELATAN" },
  // { id: "71.71", name: "KOTA MANADO" },
  // { id: "71.72", name: "KOTA BITUNG" },
  // { id: "71.73", name: "KOTA TOMOHON" },
  // { id: "71.74", name: "KOTA KOTAMOBAGU" },
  // { id: "72.01", name: "KAB. BANGGAI" },
  // { id: "72.02", name: "KAB. POSO" },
  // { id: "72.03", name: "KAB. DONGGALA" },
  // { id: "72.04", name: "KAB. TOLI TOLI" },
  // { id: "72.05", name: "KAB. BUOL" },
  // { id: "72.06", name: "KAB. MOROWALI" },
  // { id: "72.07", name: "KAB. BANGGAI KEPULAUAN" },
  // { id: "72.08", name: "KAB. PARIGI MOUTONG" },
  // { id: "72.09", name: "KAB. TOJO UNA UNA" },
  // { id: "72.10", name: "KAB. SIGI" },
  // { id: "72.11", name: "KAB. BANGGAI LAUT" },
  // { id: "72.12", name: "KAB. MOROWALI UTARA" },
  // { id: "72.71", name: "KOTA PALU" },
  // { id: "73.01", name: "KAB. KEPULAUAN SELAYAR" },
  // { id: "73.02", name: "KAB. BULUKUMBA" },
  // { id: "73.03", name: "KAB. BANTAENG" },
  // { id: "73.04", name: "KAB. JENEPONTO" },
  // { id: "73.05", name: "KAB. TAKALAR" },
  // { id: "73.06", name: "KAB. GOWA" },
  // { id: "73.07", name: "KAB. SINJAI" },
  // { id: "73.08", name: "KAB. BONE" },
  // { id: "73.09", name: "KAB. MAROS" },
  // { id: "73.10", name: "KAB. PANGKAJENE KEPULAUAN" },
  // { id: "73.11", name: "KAB. BARRU" },
  // { id: "73.12", name: "KAB. SOPPENG" },
  // { id: "73.13", name: "KAB. WAJO" },
  // { id: "73.14", name: "KAB. SIDENRENG RAPPANG" },
  // { id: "73.15", name: "KAB. PINRANG" },
  // { id: "73.16", name: "KAB. ENREKANG" },
  // { id: "73.17", name: "KAB. LUWU" },
  // { id: "73.18", name: "KAB. TANA TORAJA" },
  // { id: "73.22", name: "KAB. LUWU UTARA" },
  // { id: "73.24", name: "KAB. LUWU TIMUR" },
  // { id: "73.26", name: "KAB. TORAJA UTARA" },
  // { id: "73.71", name: "KOTA MAKASSAR" },
  // { id: "73.72", name: "KOTA PARE PARE" },
  // { id: "73.73", name: "KOTA PALOPO" },
  // { id: "74.01", name: "KAB. KOLAKA" },
  // { id: "74.02", name: "KAB. KONAWE" },
  // { id: "74.03", name: "KAB. MUNA" },
  // { id: "74.04", name: "KAB. BUTON" },
  // { id: "74.05", name: "KAB. KONAWE SELATAN" },
  // { id: "74.06", name: "KAB. BOMBANA" },
  // { id: "74.07", name: "KAB. WAKATOBI" },
  // { id: "74.08", name: "KAB. KOLAKA UTARA" },
  // { id: "74.09", name: "KAB. KONAWE UTARA" },
  // { id: "74.10", name: "KAB. BUTON UTARA" },
  // { id: "74.11", name: "KAB. KOLAKA TIMUR" },
  // { id: "74.12", name: "KAB. KONAWE KEPULAUAN" },
  // { id: "74.13", name: "KAB. MUNA BARAT" },
  // { id: "74.14", name: "KAB. BUTON TENGAH" },
  // { id: "74.15", name: "KAB. BUTON SELATAN" },
  // { id: "74.71", name: "KOTA KENDARI" },
  // { id: "74.72", name: "KOTA BAU BAU" },
  // { id: "75.01", name: "KAB. GORONTALO" },
  // { id: "75.02", name: "KAB. BOALEMO" },
  // { id: "75.03", name: "KAB. BONE BOLANGO" },
  // { id: "75.04", name: "KAB. PAHUWATO" },
  // { id: "75.05", name: "KAB. GORONTALO UTARA" },
  // { id: "75.71", name: "KOTA GORONTALO" },
  // { id: "76.01", name: "KAB. PASANGKAYU" },
  // { id: "76.02", name: "KAB. MAMUJU" },
  // { id: "76.03", name: "KAB. MAMASA" },
  // { id: "76.04", name: "KAB. POLEWALI MANDAR" },
  // { id: "76.05", name: "KAB. MAJENE" },
  // { id: "76.06", name: "KAB. MAMUJU TENGAH" },
  // { id: "81.01", name: "KAB. MALUKU TENGAH" },
  // { id: "81.02", name: "KAB. MALUKU TENGGARA" },
  // { id: "81.03", name: "KAB. KEPULAUAN TANIMBAR" },
  // { id: "81.04", name: "KAB. BURU" },
  // { id: "81.05", name: "KAB. SERAM BAGIAN TIMUR" },
  // { id: "81.06", name: "KAB. SERAM BAGIAN BARAT" },
  // { id: "81.07", name: "KAB. KEPULAUAN ARU" },
  // { id: "81.08", name: "KAB. MALUKU BARAT DAYA" },
  // { id: "81.09", name: "KAB. BURU SELATAN" },
  // { id: "81.71", name: "KOTA AMBON" },
  // { id: "81.72", name: "KOTA TUAL" },
  // { id: "82.01", name: "KAB. HALMAHERA BARAT" },
  // { id: "82.02", name: "KAB. HALMAHERA TENGAH" },
  // { id: "82.03", name: "KAB. HALMAHERA UTARA" },
  // { id: "82.04", name: "KAB. HALMAHERA SELATAN" },
  // { id: "82.05", name: "KAB. KEPULAUAN SULA" },
  // { id: "82.06", name: "KAB. HALMAHERA TIMUR" },
  // { id: "82.07", name: "KAB. PULAU MOROTAI" },
  // { id: "82.08", name: "KAB. PULAU TALIABU" },
  // { id: "82.71", name: "KOTA TERNATE" },
  // { id: "82.72", name: "KOTA TIDORE KEPULAUAN" },
  // { id: "91.01", name: "KAB. MERAUKE" },
  // { id: "91.02", name: "KAB. JAYAWIJAYA" },
  // { id: "91.03", name: "KAB. JAYAPURA" },
  // { id: "91.04", name: "KAB. NABIRE" },
  // { id: "91.05", name: "KAB. KEPULAUAN YAPEN" },
  // { id: "91.06", name: "KAB. BIAK NUMFOR" },
  // { id: "91.07", name: "KAB. PUNCAK JAYA" },
  // { id: "91.08", name: "KAB. PANIAI" },
  // { id: "91.09", name: "KAB. MIMIKA" },
  // { id: "91.10", name: "KAB. SARMI" },
  // { id: "91.11", name: "KAB. KEEROM" },
  // { id: "91.12", name: "KAB. PEGUNUNGAN BINTANG" },
  // { id: "91.13", name: "KAB. YAHUKIMO" },
  // { id: "91.14", name: "KAB. TOLIKARA" },
  // { id: "91.15", name: "KAB. WAROPEN" },
  // { id: "91.16", name: "KAB. BOVEN DIGOEL" },
  // { id: "91.17", name: "KAB. MAPPI" },
  // { id: "91.18", name: "KAB. ASMAT" },
  // { id: "91.19", name: "KAB. SUPIORI" },
  // { id: "91.20", name: "KAB. MAMBERAMO RAYA" },
  // { id: "91.21", name: "KAB. MAMBERAMO TENGAH" },
  // { id: "91.22", name: "KAB. YALIMO" },
  // { id: "91.23", name: "KAB. LANNY JAYA" },
  // { id: "91.24", name: "KAB. NDUGA" },
  // { id: "91.25", name: "KAB. PUNCAK" },
  // { id: "91.26", name: "KAB. DOGIYAI" },
  // { id: "91.27", name: "KAB. INTAN JAYA" },
  // { id: "91.28", name: "KAB. DEIYAI" },
  // { id: "91.71", name: "KOTA JAYAPURA" },
  // { id: "92.01", name: "KAB. SORONG" },
  // { id: "92.02", name: "KAB. MANOKWARI" },
  // { id: "92.03", name: "KAB. FAK FAK" },
  // { id: "92.04", name: "KAB. SORONG SELATAN" },
  // { id: "92.05", name: "KAB. RAJA AMPAT" },
  // { id: "92.06", name: "KAB. TELUK BINTUNI" },
  // { id: "92.07", name: "KAB. TELUK WONDAMA" },
  // { id: "92.08", name: "KAB. KAIMANA" },
  // { id: "92.09", name: "KAB. TAMBRAUW" },
  // { id: "92.10", name: "KAB. MAYBRAT" },
  // { id: "92.11", name: "KAB. MANOKWARI SELATAN" },
  // { id: "92.12", name: "KAB. PEGUNUNGAN ARFAK" },
  // { id: "92.71", name: "KOTA SORONG" },
];
